version: v0.8.0-alpha.2

log:
  level: debug

namespaces:
  - id: 0
    name: life_ai
  - id: 1
    name: genetica
  - id: 2
    name: human_network

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: memory
